export const menuAdmin = [
  {
    icono: 'launcher',
    color: "#fff",
    name: "Contenido",
    ruta: "",
    clase: "menuDif",
    hijo: {
      titulo: "",
      item: [
        {
          icono: "",
          name: "Crear cursos",
          color: "#fff",
          ruta: "/crear-cursos",
          hijo: {},
          claseV: "hoverAhi",
        },
        {
          icono: "",
          name: "Crear módulo",
          color: "#fff",
          ruta: "/crear-modulo-curso",
          hijo: {},
          claseV: "hoverAhi",
        },
        {
          icono: "",
          name: "Crear proyecto facultad",
          color: "#fff",
          ruta: "/crear-proyecto-facultad",
          hijo: {},
          claseV: "hoverAhi",
        },
        {
          icono: "",
          name: "Crear clases",
          color: "#fff",
          ruta: "/crear-clases",
          hijo: {},
          claseV: "hoverAhi",
        },
        {
          icono: "",
          name: "Clases grabadas",
          color: "#fff",
          ruta: "/administrar-clases-grabadas",
          hijo: {},
          claseV: "hoverAhi",
        },
        {
          icono: "",
          name: "Certificados",
          color: "#fff",
          ruta: "/crear-certificados",
          hijo: {},
          claseV: "hoverAhi",
        },
        {
          icono: "",
          name: "Cupones de descuento",
          color: "#fff",
          ruta: "/cupones-de-descuento",
          hijo: {},
          claseV: "hoverAhi",
        },
      ],
    },
  },
  {
    icono: 'launcher',
    color: "#fff",
    name: "Reportes",
    ruta: "",
    clase: "menuDif",
    hijo: {
      titulo: "",
      item: [
        {
          icono: "",
          name: "Reportes generales",
          color: "#fff",
          ruta: "/cursos-docente-motivacional",
          claseV: "hoverAhi",
          opened: false,
          hijo: {
            titulo: "Reportes generales",
            item: [
              {
                icono: "",
                name: "Reporte de alumnos matriculados",
                color: "#000",
                ruta: "/reporte-de-alumnos-matriculados",
                hijo: {},
              },
              {
                icono: "",
                name: "Reporte de inventario",
                color: "#000",
                ruta: "/reporte-de-inventario",
                hijo: {},
              },
              {
                icono: "",
                name: "Reporte de facturación",
                color: "#000",
                ruta: "/reporte-de-facturacion",
                hijo: {},
              },
              {
                icono: "",
                name: "Reporte de asistencia",
                color: "#000",
                ruta: "/reporte-de-asistencia",
                hijo: {},
              },
              {
                icono: "",
                name: "Reporte de notas",
                color: "#000",
                ruta: "/reporte-de-notas",
                hijo: {},
              },
              {
                icono: "",
                name: "Cuentas bancarias",
                color: "#000",
                ruta: "/cuentas-bancarias",
                hijo: {},
              },
            ],
          },
        },
        {
          icono: "",
          name: "Estadisticas",
          color: "#fff",
          ruta: "/cursos-docente-motivacional",
          claseV: "hoverAhi",
          opened: false,
          hijo: {
            titulo: "Estadisticas",
            item: [
              {
                icono: "",
                name: "Mejores alumnos por cursos",
                color: "#000",
                ruta: "/mejores-alumnos",
                hijo: {},
              },
              {
                icono: "",
                name: "Porcentaje de alumnos certificados",
                color: "#000",
                ruta: "/porcentaje-de-alumnos-certificados",
                hijo: {},
              },
              {
                icono: "",
                name: "Docentes mejores calificados",
                color: "#000",
                ruta: "/docentes-mejor-calificados",
                hijo: {},
              },
            ],
          },
        },
        {
          icono: "",
          name: "Calificaciones de docentes",
          color: "#fff",
          ruta: "/administracion-de-calificacion-de-docentes",
          claseV: "hoverAhi",
          hijo: {},
        },
        {
          icono: "",
          name: "Transferencia bancarias",
          color: "#fff",
          ruta: "/transferencias-bancarias",
          claseV: "hoverAhi",
          hijo: {},
        },
      ],
    },
  },
  {
    icono: 'settings',
    color: "#fff",
    name: "Comunicaciones",
    ruta: "",
    clase: "menuDif",
    hijo: {
      titulo: "",
      item: [
        {
          icono: "",
          name: "Bandeja de entrada",
          color: "#fff",
          ruta: "/cursos-docente-motivacional",
          claseV: "hoverAhi",
          opened: false,
          hijo: {
            titulo: "Bandeja de entrada",
            item: [
              {
                icono: "",
                name: "Docente",
                color: "#000",
                ruta: "/bandeja-docentes",
                hijo: {},
              },
            ],
          },
        },
        {
          icono: "",
          name: "Suscripciones",
          color: "#fff",
          ruta: "/suscripciones",
          claseV: "hoverAhi",
          hijo: {},
        },
      ],
    },
  },
  {
    icono: 'launcher',
    color: "#fff",
    name: "Accesos",
    ruta: "",
    clase: "menuDif",
    hijo: {
      titulo: "",
      item: [
        {
          icono: "",
          name: "Alumnos",
          color: "#fff",
          ruta: "/administracion-de-alumnos",
          claseV: "hoverAhi",
          hijo: {},
        },
        {
          icono: "",
          name: "Docentes",
          color: "#fff",
          ruta: "/administracion-de-docentes",
          claseV: "hoverAhi",
          hijo: {},
        },
      ],
    },
  },
];